### ISSUE TITLE
STAT table fields

### ISSUE THREAD

**Issue by LettError** [LettError/designSpaceDocument#8]
* [Looking at the STAT table in the spec](https://www.microsoft.com/typography/otspec/stat.htm)—can we store the values in the designspace file?
* Is it useful to have this data in this file? I understand there are non-variable font applications of the STAT table. 
* Is the order in which the axes elements are present in the document also good for the stat table?

Naming **regions** of an axis could be done inside an axis element. There we already know the order and which axis we're talking about. 

```xml
    <axes>
        <axis default="0" maximum="1000" minimum="0" name="width" tag="wdth">
         # name attribute contains at least one name, additional localisations are added separately?
          <region minimum="0" maximum="300" name="Light">
           <name xml:lang="de">Mager</labelname>
          </region>

          <region minimum="600" maximum="800" name="Medium"/>

          ...the other things that live here
           <labelname/>..
            <map/>..
        </axis>
    </axes>
```

**Comment by brawer** [comment]
Personally, I think this would be very useful. In fontmake, we currently don’t produce `STAT` tables at all, which means that our variable fonts are currently in violation of the OpenType 1.8 spec and won’t work on Windows. I would definitely like to fix this.

**Comment by moyogo** [comment]
The STAT table can also indicate linkedValue instead of range/region. This should also be defined somewhere.

**Comment by LettError** [comment]
Could you... sketch out some fields?

**Comment by moyogo** [comment]
Maybe this could be the structure for style axis values with ranges/regions:
```xml
<axes>
    <axis default="400" maximum="1000" minimum="1" name="weight" tag="wght">
        <styleattribute name="Light" value="200" maximum="300" minimum="0">
            <labelname xml:lang="de">Mager</labelname>
        </styleattribute>
        <styleattribute name="Regular" value="400" maximum="500" minimum="300" elidablename="true">
            <labelname xml:lang="de">Standard</labelname>
        </styleattribute>
        <styleattribute name="SemiBold" value="600" maximum="650" minimum="500">
            <name xml:lang="de">Halbfett</name>
        </styleAttribute>
        <styleattribute name="Bold" value="700" maximum="800" minimum="650">
            <name xml:lang="de">Fett</name>
        </styleAttribute>
    </axis>
</axes>
```
and this one for style axis values with linkedvalue:
```xml
<axes>
    <axis default="400" maximum="1000" minimum="1" name="weight" tag="wght">
        <styleattribute name="Light" value="200" linkedvalue="600">
            <name xml:lang="de">Mager</name>
        </styleAttribute>
        <styleattribute name="Regular" value="400" linkedvalue="700" elidablename="true">
            <name xml:lang="de">Standard</name>
        </styleAttribute>
        <styleattribute name="SemiBold" value="600">
            <name xml:lang="de">Halbfett</name>
        </styleAttribute>
        <styleattribute name="Bold" value="700">
            <name xml:lang="de">Fett</name>
        </styleAttribute>
    </axis>
</axes>
```

In theory, one could also have both region/range and a linkedvalue, for example:
```xml
<styleattribute stylename="Light" value="200" linkedvalue="600" maximum="300" minimum="0">
```
which would translate to two AxisValues in STAT, one with AxisValueFormat2 for ranges and the other with AxisValueFormat3 for the linked value.

**Comment by LettError** [comment]
Hm, I'm officially having second thoughts about this. That's a lot of name cruft that is only tangentially related to axes.

**Comment by moyogo** [comment]
Should we have this in a separate file then?

It make sense to have it in AFDKO feature syntax since it needs to be supported for non-variable fonts anyway.
/cc @brawer @behdad @anthrotype

**Comment by brawer** [comment]
Asked [Adobe](https://github.com/adobe-type-tools/afdko/issues/176) and [Monotype](https://github.com/Monotype/OpenType_Table_Source/issues/14) what they think of supporting STAT in their respective feature file formats.

**Comment by anthrotype** [comment]
as an interim solution, maybe we could store the STAT table as .ttx format in the UFO3 data folder, and merge it in the generated fonts?
https://github.com/googlei18n/ufo2ft/issues/51

**Comment by behdad** [comment]
I prefer putting it in designspace file and make designspace work for non-variable workflow. For example, not having any master elements.  Just instances...

I prefer not pushing this on Monotype and Adobe formats.  Those are far removed from how we build varfonts right now.

**Comment by LettError** [comment]
I concede there are good reasons to consider the axes. The problem is I'm not familiar with how STAT is expected to be used or implemented beyond what Peter showed. I'm concerned that this makes me responsible to implement and maintain it.

**Comment by behdad** [comment]
I'll come up with a proposal for designspace change and be happy to implement the fonttools part to take that and churn it into a STAT table.

**Comment by yarmola** [comment]
Is there any conclusion on this?

I'd like to propose two changes:

1. Please, make sure that "value" is specified for the "region", not only region range. In some cases that info can be used to create avar table. Also, having either only "value" or value + range will allow to explicitly specify which of STAT table formats is expected.

2. There should be a place to specify that some particular region is "elided". 

So I'd vote for @moyogo proposal.

**Comment by moyogo** [comment]
@behdad Did you have a proposal for designspace change?

**Comment by LettError** [comment]
Whatever you decide, changes to the spec need to be implemented in the reader and writer as well, and someone is going to have to pitch in.

**Comment by behdad** [comment]
> Please, make sure that "value" is specified for the "region", not only region range. In some cases that info can be used to create avar table. Also, having either only "value" or value + range will allow to explicitly specify which of STAT table formats is expected.

I don't think this should be used for avar.  Like rest of your points.

**Comment by behdad** [comment]
Pretty much this:
```
  <axes>
    <axis default="0" maximum="1000" minimum="0" name="width" tag="wdth">
      <labels>
          <label minimum="0" value="200" maximum="300" name="Light">
            <name xml:lang="de">Mager</labelname>
          </label>
          <label value="400" name="Regular" elidable="true" bold="700"/>
          <label value="500" name="Medium"/>
      </labels>
    </axis>
  </axes>
```

The `<label>` element, if has `name`, it reflects `en` lang tag.  Name attribute is optional, and English name can be specified using name element as well.

This handles axis value formats 1, 2, and 3.  Format 4 was added as a hack.  That attaches names to points in the designspace.  So I suggest implementing that one by reusing `<labels>` element outside of `<axes>`.  Pretty much turning it upside down.  Like:
```
  <labels>
    <label name="...">
      <location>
        <dimension name="weight" xvalue=400/>
        <dimension.../>
      </location>
      <name xml:lang.../>
    </label>
  </labels>
```
This takes care of generating format 4.

@anthrotype @moyogo @LettError How does this sound?

**Comment by behdad** [comment]
Also allow `order` attribute on `axis` element.

**Comment by LettError** [comment]
what does `elidable` mean?

**Comment by yarmola** [comment]
elidable means that the label should not be used to make style name, like "Regular" for weight axis

however, we need to supply the "elidedName" for the font, which is used as style name if style name that is made from axis names is empty.

**Comment by yarmola** [comment]
> I don't think this should be used for avar

I agree

**Comment by yarmola** [comment]
> Also allow order attribute on axis element.

maybe actual ordering of axis entries is the `order`?

**Comment by behdad** [comment]
> Also allow order attribute on axis element.
> maybe actual ordering of axis entries is the order?

The actual order is what will get encoded in fvar and STAT tables.  This order attribute will go directly in the axisOrder field of the STAT axis record.

**Comment by LettError** [comment]
So.. there are 2 different types of order to document?

**Comment by behdad** [comment]
So.. there are 2 different types of order to document?
> So.. there are 2 different types of order to document?
The order of element is insignificant in the final product.  Why the working group felt that it shouldn't be used for presentation escapes me now.  I'm guessing just "because". Ie. we said these must match the fvar order, and fvar might be already existing in fonts, so let's just encoded the presentation order separately blah blah.

Or think of it this way, yeah I like this explanation: the order of axis elements is the order you might want to shows the different axes to the user.  Ie. for slider purposes.  The axisOrder thing is the order to combine labels for axes to get style names.  Ie. you can decide to get "Bold Condensed" and not "Condensed Bold", even if you want your Width axis slider to be shown before your Weight axis slider.  Yeah, I'm happy with this explanation.   I think @sairuspatel have had asked before and I didn't have a good explanation.

**Comment by behdad** [comment]
> elidable means that the label should not be used to make style name, like "Regular" for weight axis
> 
> however, we need to supply the "elidedName" for the font, which is used as style name if style name that is made from axis names is empty.

There's some history and misfortune behind the whole elidable thing.  Originally the field was added for names that "should be elided if there's at least some other name".  Eg, "Normal" stretch.  You never say "Bold Normal", just "Bold".  The idea was that if no name is left, then one of the elided ones will be used.  That was supposed to be how you'd get "Regular".  However, if multiple axes are present and all have elidable names, like "Regular Normal", then it's not clear which one to pick, so that's why later on the `elidedName` field was added.  We should put that somewhere.  Maybe an `<elidedName>` element that has name attribute and name elements.  It's ugly but works.

**Comment by LettError** [comment]
I'm sorry I may be too obtuse to comprehend elision. Maybe before the ugly is added to this spec, what might be useful is a bit of testing code that illustrates how this sample data transforms into font names based on a given designspace location? Because I'm still ¯\_(ツ)_/¯

**Comment by behdad** [comment]
> I'm sorry I may be too obtuse to comprehend elision. Maybe before the ugly is added to this spec, what might be useful is a bit of testing code that illustrates how this sample data transforms into font names based on a given designspace location? Because I'm still ¯_(ツ)_/¯

Yes, good point.  I'll make sure to write a tool to do that when we implement this in varLib.designspace.

**Comment by behdad** [comment]
@readroberts

**Comment by readroberts** [comment]
This proposal looks good to me. Behdad mentioned in another thread that he hoped to provide an implementation soon - I'll be ready to try it out as soon as it is available. 

I think that two STAT table items are still missing: the 'flags'  bit OLDER_SIBLING_FONT_ATTRIBUTE, and the header elidedFallbackNameID. The former could be another label element attribute (older_sibling="true"?). The latter could be a new attribute of <axes> (elided_fallback="Regular"> ?).

**Comment by behdad** [comment]
> I think that two STAT table items are still missing: the 'flags' bit OLDER_SIBLING_FONT_ATTRIBUTE, and the header elidedFallbackNameID. The former could be another label element attribute (older_sibling="true"?). The latter could be a new attribute of (elided_fallback="Regular"> ?).

The elided is discussed in https://github.com/LettError/designSpaceDocument/issues/8#issuecomment-334187072
We can add a older_sibling="true" or something.

At this time, looking for volunteers to start implementing this in varLib.designspace.  I can then look into the varLib part.

**Comment by behdad** [comment]
Started generating very basic STAT table, with no further data than just the fvar axes.  To implement the rest we need to flesh out varLib.designspace to basically be a replacement for this repo.  Otherwise the code will become even more spaghetti. (no offense to spaghetti!)

**Comment by madig** [comment]
I am throwing around some ideas in my head on how to best support `STAT` table generation from a Designspace and used Behdad's idea above to sketch out some example Designspace files in the fictitious format `"5.0"`. Maybe we can even enhance Designspace as a format if we place `STAT` information front and center?

I think there are three different use-cases that a Designspace needs to support:

- Designspace for a full variable font that contains everything.
- Several Designspaces for several distinct VFs ...
  - ... that belong to the same family but aren't compatible on the outline-level (e.g. upright and italic)
  - ... that may have been added after the initial design but may not be outline-compatible with the old releases.
  - ... which actually are compatible but that you want to partition into several Designspaces because you want to offer several editions (everything, just upright, just italic, ...)
- Static fonts for both cases above.

## Sketches

In the following sketches, I removed all tag attributes I found redundant. The only thing that has to be looked up in the UFO is the family name, all other attributes should be computed from the information in the file. It should still be possible to override e.g. the Postscript font name, but the default should have something sensible and pre-computed.

### Designspace contains whole family

Here I took the Designspace of one of our fonts and sketched it up:

[Venn.txt](https://github.com/LettError/designSpaceDocument/files/2860664/Venn.txt)

Notes:

1. The labels are assigned in design space, because design space coordinates are used to define instances, so matching them is easier.
2. These labels are all format 1, except the label that uses "linkedvalue", which needs format 3.

#### Example for format 4 axis values

I think format 4 has been invented to support Decovar.

[DecovarAlpha.txt](https://github.com/LettError/designSpaceDocument/files/2860670/DecovarAlpha.txt)

Notes:

1. Here, I defined the labels outside the axis and then refer to them in the instances. I'm not sure about this, maybe it's better to add a `label` tag to instances like this:

```XML
    <instance>
      <label value="Default" /> <!-- Adds a format 4 STAT entry at this location -->
      <location>
        <dimension name="Inline Skeleton" xvalue="0" />
        <dimension name="Worm Skeleton" xvalue="0" />
        <dimension name="Stripes" xvalue="0" />
        <dimension name="Rounded" xvalue="0" />
        <dimension name="Flared" xvalue="0" />
        <dimension name="Rounded Slab" xvalue="0" />
        <dimension name="Shearded" xvalue="0" />
        <dimension name="Bifurcated" xvalue="0" />
        <dimension name="Open Inline Terminal" xvalue="0" />
        <dimension name="Slab" xvalue="0" />
        <dimension name="Inline Terminal" xvalue="0" />
        <dimension name="Worm Terminal" xvalue="0" />
        <dimension name="Weight" xvalue="0" />
        <dimension name="Inline" xvalue="0" />
        <dimension name="Worm" xvalue="0" />
      </location>
    </instance>
```

### Designspace contains parts of the family

Here I looked at the `STAT` table of the SourceSansVariable(Roman|Italics) fonts and sketched up their Designspace files.

[SourceSansRoman.txt](https://github.com/LettError/designSpaceDocument/files/2860671/SourceSansRoman.txt)
[SourceSansItalic.txt](https://github.com/LettError/designSpaceDocument/files/2860672/SourceSansItalic.txt)

Notes:

1. The weight axis contains two labels for "Regular" because format 2 does not provide a `LinkedValue` field. I've raised this here: https://github.com/adobe-fonts/source-sans-pro/issues/164#issuecomment-463006052. It's violating the current `STAT` specification -- maybe this should not be supported in designspaceLib?

### Separate file for defining axis labels?

Maybe it's worth defining a new file format to collect the information for all axes, a Stylespace so to speak? The file contains the same information as a Designspace that contains a complete family but can be shared between different (subset) Designspaces.

Or maybe not?

## Potential Problems

I think the biggest impedance mismatch would be that no editor I know of separates out the individual style names for each axis, e.g. in Glyphs, you name your instances "Extra Bold Compressed" etc. instead of ("Extra Bold", "Compressed"). I'd have to implement some form of string splitting and guessing in glyphsLib to scrape the info back out (we need more of that in glyphsLib).

What do you think?

**Comment by moyogo** [comment]
@madig I think we can open a new issue for fonttools instead of here.
